name: set-up-oidc
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
jobs:
  account-check-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Identify dev account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.DEV_AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: "us-east-1"
          EXPECTED_ACCOUNT_ID: ${{ vars.DEV_AWS_ACCOUNT_ID }}
        working-directory: oidc
        run: |
          npm run account-check
  account-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Identify dev account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.TEST_AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: "us-east-1"
          EXPECTED_ACCOUNT_ID: ${{ vars.TEST_AWS_ACCOUNT_ID }}
        working-directory: oidc
        run: |
          npm run account-check
  set-up-oidc:
    runs-on: ubuntu-latest
    needs: [account-check-dev, account-check-test]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: oidc
        run: |
          npm install
      - name: Build
        working-directory: oidc
        run: |
          npm run build
      - name: Test
        working-directory: oidc
        run: |
          npm test
      